### ISSUE TITLE
Output json is not parsable

### ISSUE THREAD

**Issue by hacktek** [deathlyface/python-tradingview-ta#34]
Hi!

Looks like the output json uses single quotes (') and that causes issues when feeding the json to an external program (jq) or python module (json.tool).

Normal output:

```
$ ./btcstats.py
{'RECOMMENDATION': 'BUY', 'BUY': 13, 'SELL': 4, 'NEUTRAL': 9}
```

Feeding to jq:

```
$ ./btcstats.py | jq .
parse error: Invalid numeric literal at line 1, column 18
```

Feeding to json.tool:

```
$ ./btcstats.py | python -m json.tool
Expecting property name: line 1 column 2 (char 1)
```

Trying to parse on https://jsonlint.com/ returns the following:

```
Error: Parse error on line 1:
{	'RECOMMENDATION': 'B
--^
Expecting 'STRING', '}', got 'undefined'
```

Changing the quotes to double (") fixes it.

A workaround is to use sed and replace the single quotes.

```
$ ./btcstats.py | sed 's/\x27/"/g' | jq .
{
  "RECOMMENDATION": "BUY",
  "BUY": 12,
  "SELL": 5,
  "NEUTRAL": 9
}
```

**Comment by deathlyface** [comment]
Hey @hacktek,

This error has nothing to do with tradingview-ta. It's because of how python is designed. The output of tradingview-ta (or btcstats.py), is a python dictionary, not JSON. By default, python uses single quotes, so if I create a python dictionary with double quotes, python will convert it into single quotes.
```python
import json

# Create a test dictionary
test_dict = {"key": "value"}

# Print the dictionary
print(test_dict)
# Print output: {'key': 'value'}

# Convert dictionary to JSON, then print
test_json = json.dumps(test_dict)
print(test_json)
# Print output: {"key": "value"}
```
Please see this [tutorial](https://pythonexamples.org/python-dict-to-json/) on how to convert a python dictionary into JSON. Please let me know if you have another question.

**Comment by hacktek** [comment]
ah that makes sense, it didn't actually occur to me to use the builtin json parsing!

Thanks for the prompt response.

**Comment by deathlyface** [comment]
Glad to help.
